### ISSUE TITLE
Compilation Errors From Analog Input Channels for AVR MCU / RAMPS

### ISSUE THREAD

**Issue by jimzim111** [Paciente8159/uCNC-config-builder#32]
When configuring analog input for a ATmega/RAMPS board, all options for the channel result in compliation errors.

Leaving the channel selection blank leads to errors like:
`mcumap_avr.h:4760:24: error: 'ANALOG0_CHANNEL' undeclared (first use in this function); did you mean 'ANALOG0_INREG'?`

Selecting channel A/B/C/D leads to:
`src/core/io_control.c: In function 'io_get_pinvalue':
boardmap_overrides.h:86:25: error: 'B' undeclared (first use in this function)
 #define ANALOG0_CHANNEL B`

It can compile successfully by adding to boardmap_overrides.h:
`#define ANALOG0_CHANNEL 0` 

But it's not clear what side effects that may cause, and I haven't yet tested whether any analog input really works on the board when doing this.

Does this seem like an issue with the selection options in the config builder?  Or an issue with how a blank selection is handled in the firmware build?  Or something else?

Thanks!

[uCNC config.zip](https://github.com/user-attachments/files/17926749/uCNC.config.zip)
[ucnc_build.json](https://github.com/user-attachments/files/17926754/ucnc_build.json)

**Comment by Paciente8159** [comment]
Thanks for reporting this. I'll check out.

**Comment by Paciente8159** [comment]
Hi there. The AVR analog channel list was incorrect indeed.
I've patched the Web Builder here https://github.com/Paciente8159/uCNC-config-builder/commit/9ad2e97f9d6a134a39a2809340b9b1c461493de4

Thanks.

**Comment by jimzim111** [comment]
Nice, thank you for the update.
